Traceback (most recent call last):
  File "/data/lsancere/miniconda3/envs/histo-miner-env-2/lib/python3.10/site-packages/pudb/__init__.py", line 158, in runscript
    dbg._runscript(mainpyfile)
  File "/data/lsancere/miniconda3/envs/histo-miner-env-2/lib/python3.10/site-packages/pudb/debugger.py", line 526, in _runscript
    self.run(statement)
  File "/data/lsancere/miniconda3/envs/histo-miner-env-2/lib/python3.10/bdb.py", line 597, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "evaluate_hovernet.py", line 113, in <module>
    prednum_labels, prednpy_geneinstmap = cv2.connectedComponents(prednpy_genebin_instmap, connectivity=8)
cv2.error: OpenCV(4.8.1) /io/opencv/modules/imgproc/src/connectedcomponents.cpp:5632: error: (-215:Assertion failed) iDepth == CV_8U || iDepth == CV_8S in function 'connectedComponents_sub1'

